### ISSUE TITLE
[Bug] Remove CC0-1.0 licenses for unlicensed work from OMEX metadata/RDF files

### ISSUE THREAD

**Issue by jonrkarr** [virtualcell/vcdb#11]
The metadata for `12119723` indicates license `CC0-1.0`. However, my understanding is that license information is not known for the VCell database. In that case, models should be considered to have no license.

The following XML should be removed
```
<dc:license>
    <rdf:Description>
	<dc:identifier rdf:resource="http://identifiers.org/spdx:CC0-1.0"/>
	<rdfs:label>CC0-1.0</rdfs:label>
    </rdf:Description>
</dc:license>
```

**Comment by danv61** [comment]
License entry removed.
